### PR TITLE
Package manager compatibility

### PR DESCRIPTION
**Pull request by thijse**
Hi,

I've added PlatformIO Library Registry manifest file, and made the library compatible with the updated (rev. 2) 1.5.x library format, so that it can be submitted for the Arduino Package Manager.

If you could you pull these changes and publish your library

to the Arduino package list
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

and PlatformIo package list
http://docs.platformio.org/en/latest/librarymanager/creating.html#register

I could refer to these in my CmdMessenger library

ps.
Great library and awesome explanation on PID!

### CODE REVIEW

**Comment by thijse** [comment]
Great, thanks!

**Comment by Lauszus** [comment]
Note however that you still need to move all the content into the root of this repository and then create a tag. Then you need to open up an issue at the Arduino repository with a request to get it included.

Please see: https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager.

**Comment by thijse** [comment]
Thanks Lauszus, I had not seen that. I personally think it is a serious limitation of the Arduino package system, having to put packages in the root of a repository. Nevertheless, Brett, are you willing to move the code, tag it and open up an issue at the Arduino repository?

**Comment by br3ttb** [comment]
I have moved the code.  it has been a LONG time since I have pushed to
github or worked in the arduino space. Can someone please give me a
confirmation that this looks like the library manager will accept it before
I go and create a tag?

On Mon, Apr 20, 2015 at 10:25 AM, Thijs Elenbaas <notifications@github.com>
wrote:

> Thanks Lauszus, I had not seen that. I personally think it is a serious
> limitation of the Arduino package system, having to put packages in the
> root of a repository. Nevertheless, Brett, are you willing to move the
> code, tag it and open up an issue at the Arduino repository?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/br3ttb/Arduino-PID-Library/pull/24#issuecomment-94466814>
> .
>



-- 
Brett

**Comment by Lauszus** [comment]
@br3ttb yes it looks correct ;)

**Comment by thijse** [comment]
Great!

Ive submitted a request to add it to the Arduino Library Manager:

https://github.com/arduino/Arduino/issues/3035

**Pull request merged**
